import test from 'node:test';import assert from 'node:assert/strict';import {JSDOM} from 'jsdom';import {readFile} from 'node:fs/promises';
import {lifecycleFixture} from './helpers/lifecycle-fixture.mjs';
import {assertPublicRegistry,registryResponse} from '../assets/js/registry-public.mjs';
import {orderedProducts} from '../assets/js/registry-order.mjs';import {mixedCards} from '../assets/js/writing-model.mjs';
import {unavailableCard,recoverySections,productActions,setupProductLifecycle} from '../assets/js/product-lifecycle.mjs';
test('lifecycle RPC: reversible cycles preserve data, ranks and mixed slots; invalid/stale/direct writes denied',async()=>{const f=await lifecycleFixture();try{
 const initial=await f.rows(),home=(await f.state()).home_order,id=f.ids[2];
 const facts=rows=>rows.map(({archived,lifecycle_state,restore_state,deleted_at,lifecycle_revision,updated_at,...p})=>p);
 for(let cycle=0;cycle<2;cycle++)for(const action of ['hide','show','hide','archive','restore','delete','restore','show','archive','delete','restore']){
  const response=await f.change(id,action);assert.equal(response.status,200,action);assert.deepEqual(facts(await f.rows()),facts(initial));assert.deepEqual((await f.state()).home_order,home);
  const p=(await f.rows()).find(p=>p.id===id);assert.equal(p.archived,['archived','deleted'].includes(p.lifecycle_state));assert.equal(!!p.deleted_at,p.lifecycle_state==='deleted');
 }
 const current=(await f.rows()).find(p=>p.id===id);assert.equal((await f.change(id,'restore')).status,400);assert.equal((await f.change(id,'hide',{revision:current.lifecycle_revision-1})).status,409);
 for(const token of ['', 'other','forged','anonymous'])assert.ok([401,403].includes((await f.request(f.registry,{operation:'lifecycle',data:{id,revision:current.lifecycle_revision,action:'hide'}},token)).status));
 assert.equal((await f.request(f.registry,{operation:'lifecycle',data:{id,revision:current.lifecycle_revision,action:'delete'}})).status,422);
 for(const role of ['anon','authenticated']){await f.db.exec('set role '+role);await assert.rejects(f.db.query("select * from change_product_lifecycle($1,0,'hide')",[id]),/permission denied/);await assert.rejects(f.db.exec('select * from product_registry'),/permission denied/);await f.db.exec('reset role');}
 await assert.rejects(f.db.query("update product_registry set lifecycle_state='deleted' where id=$1",[id]),/check constraint/);
 }finally{await f.db.close()}});
test('public API redacts hidden to four fields, omits archived/deleted and private mixed IDs; owner retains real data',async()=>{const f=await lifecycleFixture();try{
 await f.change(f.ids[1],'hide');await f.change(f.ids[2],'archive');await f.change(f.ids[3],'delete');
 const pub=assertPublicRegistry(await (await f.request(f.registry,{operation:'read-public',contract:'lifecycle-v1'},'')).json());assert.equal(pub.products.length,3);
 assert.deepEqual(Object.keys(pub.products.find(p=>p.id===f.ids[1])).sort(),['id','lifecycleState','name','sortOrder']);assert.equal(pub.products.find(p=>p.id===f.ids[1]).name,'QA Product B');
 const legacy=await(await f.request(f.registry,{operation:'read-public'},'')).json();assert.equal(legacy.products.length,2);assert.equal(legacy.products.some(p=>'lifecycleState' in p),false);
 const owner=await (await f.request(f.registry,{operation:'read-owner'})).json();assert.equal(owner.products.length,5);assert.equal(owner.presentationRevision,(await f.state()).revision);const manager=await(await f.request(f.registry,{operation:'read-owner'},'qa-manager')).json();assert.equal(manager.presentationRevision,owner.presentationRevision);assert.equal(owner.products[1].description,'Isolated product description 1');assert.equal(owner.products[1].mainUrl,'https://example.invalid/1');assert.equal(orderedProducts(owner.products).length,3);
 const settings=await (await f.request(f.writing,{operation:'read-public'},'')).json();assert.deepEqual(settings.home_order,[f.ids[0],'writing',f.ids[1],f.ids[4]]);
 const html=unavailableCard(owner.products[1]);const dom=new JSDOM(html);assert.equal(dom.window.document.querySelectorAll('a,img,button,.badge,.meta-list').length,0);assert.equal(dom.window.document.body.textContent,'UNAVAILABLEQA Product B');assert.doesNotMatch(html,/example.invalid|description|qa-product|Isolated note/);
 const recovery=recoverySections(owner.products);assert.match(recovery,/Archived \(1\)/);assert.match(recovery,/Deleted Items \(1\)/);assert.equal(new JSDOM(recovery).window.document.querySelectorAll('[data-lifecycle=restore]').length,2);assert.match(productActions(owner.products[1]),/Show to guests/);
 assert.throws(()=>assertPublicRegistry({...pub,products:[{...pub.products[1],description:'leak'}]}),/Hidden product metadata/);
 }finally{await f.db.close()}});
test('multiple inactive slots survive active reorder, restores, conflicts and legacy Registry reorder',async()=>{const f=await lifecycleFixture();try{
 const original=(await f.state()).home_order;await f.change(f.ids[1],'archive');await f.change(f.ids[3],'delete');let state=await f.state();const next=[f.ids[4],'writing',f.ids[2],f.ids[0]];
 const saved=await f.request(f.writing,{operation:'home-order',revision:state.revision,data:next});assert.equal(saved.status,200);assert.deepEqual((await f.state()).home_order,[f.ids[4],'writing',f.ids[1],f.ids[2],f.ids[3],f.ids[0]]);
 assert.equal((await f.request(f.writing,{operation:'home-order',revision:state.revision,data:next})).status,409);
 await f.change(f.ids[1],'restore');await f.change(f.ids[3],'restore');assert.deepEqual((await f.state()).home_order,[f.ids[4],'writing',f.ids[1],f.ids[2],f.ids[3],f.ids[0]]);
 state=await f.state();await f.request(f.writing,{operation:'home-order',revision:state.revision,data:original});await f.change(f.ids[2],'archive');const rows=await f.rows(),active=rows.filter(p=>!p.archived);const reorder=await f.request(f.registry,{operation:'reorder',data:{presentationRevision:(await f.state()).revision,expected:active.map(p=>({id:p.id,sortOrder:p.sort_order})),order:active.map(p=>p.id).reverse()}});assert.equal(reorder.status,200);const hidden=(await f.rows()).find(p=>p.id===f.ids[2]);assert.equal(hidden.sort_order,30);await f.change(f.ids[2],'restore');assert.equal((await f.state()).home_order.indexOf(f.ids[2]),original.indexOf(f.ids[2]));assert.deepEqual((await f.state()).settings,{featured_slug:'qa-first',article_order:['qa-first']});
 }finally{await f.db.close()}});
test('stale static fallback contains no products; build refuses records even if previously public-safe',async()=>{const snapshot=JSON.parse(await readFile(new URL('../dist/data/registry.public.snapshot.json',import.meta.url),'utf8'));assert.deepEqual(assertPublicRegistry(snapshot).products,[]);const html=await readFile(new URL('../index.html',import.meta.url),'utf8');assert.doesNotMatch(html,/fetch\('\/data\/registry.public.snapshot.json/);assert.match(html,/render\(emptyRegistry\(\)\)/);});
test('legacy reorder rejects a stale mixed revision even when product ranks have not changed',async()=>{const f=await lifecycleFixture();try{const rows=await f.rows(),before=await f.state();const next=[...before.home_order].reverse();assert.equal((await f.request(f.writing,{operation:'home-order',revision:before.revision,data:next})).status,200);const stale=await f.request(f.registry,{operation:'reorder',data:{presentationRevision:before.revision,expected:rows.map(p=>({id:p.id,sortOrder:p.sort_order})),order:rows.map(p=>p.id)}});assert.equal(stale.status,409);assert.deepEqual((await f.state()).home_order,next);}finally{await f.db.close()}});
test('lifecycle UI confirms deletion, cancels on logout, clears private dialog text and ignores late saves',async()=>{
 const dom=new JSDOM('<div id="root"><button data-lifecycle="delete" data-id="p">Delete</button><button data-lifecycle="hide" data-id="p">Hide</button></div><p id="lifecycle-status"></p>');const w=dom.window;Object.assign(globalThis,{document:w.document,window:w});
 w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(value){this.returnValue=value;this.open=false;this.dispatchEvent(new w.Event('close'))};
 let calls=0,resolveSave,saved=0;const ui=setupProductLifecycle({root:document.getElementById('root'),getProducts:()=>[{id:'p',name:'Private archived name',lifecycleRevision:0}],getOwner:()=>({save(){calls++;return new Promise(r=>resolveSave=r)}}),onSaved:()=>saved++,onBusy:()=>{}});const tick=()=>new Promise(r=>setTimeout(r,0));
 ui.setOwner(true);document.querySelector('[data-lifecycle=delete]').click();assert.equal(document.querySelector('dialog').open,true);ui.setOwner(false);await tick();assert.equal(calls,0);assert.equal(document.querySelector('dialog p').textContent,'');
 ui.setOwner(true);document.querySelector('[data-lifecycle=delete]').click();document.querySelector('dialog').close('delete');await tick();assert.equal(calls,1);ui.setOwner(false);resolveSave({ok:true,products:[{id:'p',lifecycleState:'deleted'}]});await tick();assert.equal(saved,0);assert.equal(document.getElementById('lifecycle-status').textContent,'');dom.window.close();
});
