import test from 'node:test';import assert from 'node:assert/strict';import {JSDOM} from 'jsdom';import {readFile} from 'node:fs/promises';
import {articleEditor,replaceInline} from '../assets/js/writing-editor.mjs';
import {parseArticle,serializeArticle,articleHtml} from '../assets/js/writing-content.mjs';
import {setupWriting} from '../assets/js/writing.mjs';
const source=await readFile(new URL('fixtures/content/writing/qa-first.md',import.meta.url),'utf8');const article=parseArticle(source);const tick=()=>new Promise(r=>setTimeout(r,20));
function env(url='https://main.example.invalid/writing/qa-first/'){const dom=new JSDOM('<body><div id="reorder-toolbar"></div>',{url}),w=dom.window;Object.assign(globalThis,{window:w,document:w.document,location:w.location,history:w.history,FormData:w.FormData});w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.HTMLElement.prototype.scrollIntoView=function(){};return dom}
test('safe tags block lists roundtrip and absent tags stay absent; duplicate/nested/object metadata rejected',()=>{
 const s=source.replace('slug:', 'tags:\n  - AI\n  - "Architecture"\n  - Education\nslug:');const a=parseArticle(s);assert.deepEqual(a.tags,['AI','Architecture','Education']);assert.deepEqual(parseArticle(serializeArticle(a)).tags,a.tags);assert.equal(Object.hasOwn(parseArticle(serializeArticle(article)),'tags'),false);
 for(const tags of ['tags:\n  - AI\n  - AI\n','tags:\n  - {evil: yes}\n','tags:\n    - nested\n','tags: [AI]\n'])assert.throws(()=>parseArticle(source.replace('slug:',tags+'slug:')));
});
test('article title/body/excerpt/date/category/video/social edits submit while tags remain outside editable fields',async()=>{
 const dom=env();let saved;const form=articleEditor({article:{...article,tags:['AI']},assets:[],save:async(data,uploads)=>{saved={data,uploads}},cancel(){},isCurrent:()=>true});document.body.append(form);
 for(const [key,value] of Object.entries({title:'Corrected title',body:'A corrected paragraph.',excerpt:'Corrected summary.',date:'2026-09-17',category:'Education',video_url:'https://video.example.invalid/v',linkedin_url:'https://www.linkedin.com/posts/corrected',facebook_url:'https://www.facebook.com/post'}))form.elements.namedItem(key).value=value;
 form.dispatchEvent(new dom.window.Event('submit',{cancelable:true}));await tick();assert.equal(saved.data.title,'Corrected title');assert.equal(saved.data.body,'A corrected paragraph.');assert.equal(saved.data.excerpt,'Corrected summary.');assert.equal(saved.data.video_url,'https://video.example.invalid/v');assert.match(saved.data.linkedin_url,/corrected/);assert.equal(Object.hasOwn(saved.data,'tags'),false);dom.window.close();
});
test('cover asset selection and inline URL replacements avoid hand editing Markdown paths',()=>{
 const dom=env(),form=articleEditor({article,assets:['/writing/qa-first/cover.webp'],save(){},cancel(){},isCurrent:()=>true});document.body.append(form);const select=form.querySelector('[data-cover-asset]');select.value='/writing/qa-first/cover.webp';select.dispatchEvent(new dom.window.Event('change'));assert.equal(form.elements.namedItem('cover').value,select.value);
 const image=form.querySelector('[data-inline] input[type=text]');assert.ok(image);image.value='https://images.example.invalid/replacement.webp';image.dispatchEvent(new dom.window.Event('change'));assert.match(form.elements.namedItem('body').value,/https:\/\/images.example.invalid\/replacement.webp/);assert.throws(()=>replaceInline(article.body,'a','javascript:bad'));dom.window.close();
});
test('cover and inline file uploads submit immutable per-article assets and updated references',async()=>{
 const dom=env();let saved;const form=articleEditor({article,assets:[],save:async(data,uploads)=>{saved={data,uploads}},cancel(){},isCurrent:()=>true});document.body.append(form);
 for(const input of [form.querySelector('[data-cover-upload]'),form.querySelector('[data-inline] input[type=file]')]){Object.defineProperty(input,'files',{value:[{size:8,type:'image/png',arrayBuffer:async()=>new Uint8Array([137,80,78,71,13,10,26,10]).buffer}]});input.dispatchEvent(new dom.window.Event('change'));await tick()}
 form.dispatchEvent(new dom.window.Event('submit',{cancelable:true}));await tick();assert.equal(saved.uploads.length,2);assert.match(saved.data.cover,/^\/writing\/qa-first\/replacement-[a-f0-9]+\.png$/);assert.match(saved.data.body,/replacement-[a-f0-9]+\.png/);assert.notEqual(saved.uploads[0].name,saved.uploads[1].name);dom.window.close();
});
test('logout during file preparation or save never re-enables controls or submits later',async()=>{
 const dom=env();let current=true,saves=0,resolve;const form=articleEditor({article,assets:[],save:async()=>{saves++},cancel(){},isCurrent:()=>current});document.body.append(form);const input=form.querySelector('[data-cover-upload]');Object.defineProperty(input,'files',{value:[{size:8,type:'image/png',arrayBuffer:()=>new Promise(r=>{resolve=r})}]});input.dispatchEvent(new dom.window.Event('change'));current=false;resolve(new Uint8Array(8).buffer);await tick();form.dispatchEvent(new dom.window.Event('submit',{cancelable:true}));assert.equal(saves,0);assert.equal(form.querySelector('[type=submit]').disabled,true);dom.window.close();
});
test('owner controls are contextual only; guests cannot open editor; logout rejects late article reads',async()=>{
 const dom=env(),oldFetch=globalThis.fetch;let pending;const projection={ok:true,settings:{},home_order:[]};globalThis.fetch=async(url)=>Response.json(url.endsWith('writing-content')?{schema:1,articles:[{...article,reader_html:articleHtml(article)}]}:projection);
 try{const writing=setupWriting({url:'https://api.example.invalid',key:'public',getOwner:()=>({writingRequest:async p=>p.operation==='read-owner'?{...projection,revision:0}:new Promise(r=>{pending=r})}),onChange(){},onAvailability(){}});await writing.ready;assert.equal([...document.querySelectorAll('button')].some(b=>/Edit Article|Writing settings/.test(b.textContent)),false);writing.setOwner(true);await tick();assert.equal(document.querySelector('#reorder-toolbar').textContent,'');const edit=[...document.querySelectorAll('button')].find(b=>b.textContent==='Edit Article');assert.ok(edit);edit.click();writing.setOwner(false);pending({ok:true,revision:'blob',article,assets:[]});await tick();assert.equal(document.querySelector('.article-edit-form'),null);assert.equal([...document.querySelectorAll('button')].some(b=>/Edit Article|Set as MAIN cover|Reorder articles/.test(b.textContent)),false)}finally{globalThis.fetch=oldFetch;dom.window.close()}
});
test('contextual feature/order writes patch independent settings without home or article source writes',async()=>{
 const dom=env(),oldFetch=globalThis.fetch,requests=[];const projection={ok:true,settings:{},home_order:['writing','product']};globalThis.fetch=async url=>Response.json(url.endsWith('writing-content')?{schema:1,articles:[{...article,reader_html:articleHtml(article)},{...article,slug:'newer',date:'2026-09-19',reader_html:'<h1>Newer</h1>'}]}:projection);
 try{const writing=setupWriting({url:'https://api.example.invalid',key:'public',getOwner:()=>({writingRequest:async p=>{requests.push(p);return {...projection,revision:requests.length,settings:p.data||{}}}}),onChange(){},onAvailability(){}});await writing.ready;writing.setOwner(true);await tick();[...document.querySelectorAll('button')].find(b=>b.textContent==='Set as MAIN cover').click();await tick();assert.deepEqual(requests.at(-1).data,{featured_slug:article.slug});[...document.querySelectorAll('button')].find(b=>b.textContent==='Reorder articles').click();document.querySelector('.writing-order-form').dispatchEvent(new dom.window.Event('submit',{cancelable:true}));await tick();assert.deepEqual(requests.at(-1).data,{article_order:['newer',article.slug]});assert.ok(requests.every(p=>!['home-order','save-article'].includes(p.operation)))}finally{globalThis.fetch=oldFetch;dom.window.close()}
});

test('navigating away invalidates a pending article read without waiting for logout',async()=>{
 const dom=env(),oldFetch=globalThis.fetch;let pending;const second={...article,slug:'second',title:'Second article',reader_html:'<h1>Second article</h1>'};const projection={ok:true,settings:{},home_order:[]};globalThis.fetch=async url=>Response.json(url.endsWith('writing-content')?{schema:1,articles:[{...article,reader_html:articleHtml(article)},second]}:projection);
 try{const writing=setupWriting({url:'https://api.example.invalid',key:'public',getOwner:()=>({writingRequest:async p=>p.operation==='read-owner'?{...projection,revision:0}:new Promise(r=>{pending=r})}),onChange(){},onAvailability(){}});await writing.ready;writing.setOwner(true);await tick();[...document.querySelectorAll('button')].find(b=>b.textContent==='Edit Article').click();document.querySelector('a[href="/writing/second/"]').click();pending({ok:true,revision:'blob',article,assets:[]});await tick();assert.equal(location.pathname,'/writing/second/');assert.equal(document.querySelector('.article-edit-form'),null);assert.match(document.querySelector('.writing-reader').textContent,/Second article/)}finally{globalThis.fetch=oldFetch;dom.window.close()}
});
