import test from 'node:test';import assert from 'node:assert/strict';import {JSDOM} from 'jsdom';
import {articleOrder,featuredArticle,writingCard,defaults} from '../assets/js/writing-model.mjs';
import {setupWriting} from '../assets/js/writing.mjs';import {lifecycleFixture} from './helpers/lifecycle-fixture.mjs';
const articles=['a','b','c'].map((slug,i)=>({slug,title:slug.toUpperCase(),date:['2026-09-01','2026-09-05','2026-09-10'][i],featured:i===0,display_order:3-i,cover:'/writing/'+slug+'/cover.webp',cover_alt:'Cover '+slug,category:'Category '+slug,excerpt:'Excerpt '+slug,reader_html:'<h1>'+slug+'</h1>'}));
const slugs=rows=>rows.map(a=>a.slug),tick=()=>new Promise(r=>setTimeout(r,30));
test('default date descending ignores legacy featured/display order and uses slug for equal dates without mutating input',()=>{const rows=[...articles,{...articles[2],slug:'aa'}],before=structuredClone(rows);assert.deepEqual(slugs(articleOrder(rows)),['aa','c','b','a']);assert.deepEqual(rows,before);});
test('manual relative order survives repeated new insertions and absent manual slugs',()=>{const settings={article_order:['b','removed','a']};assert.deepEqual(slugs(articleOrder(articles,settings)),['c','b','a']);const d={...articles[0],slug:'d',date:'2026-09-12'},e={...d,slug:'e',date:'2026-09-15'};assert.deepEqual(slugs(articleOrder([...articles,d],settings)),['d','c','b','a']);assert.deepEqual(slugs(articleOrder([...articles,d,e],settings)),['e','d','c','b','a']);assert.deepEqual(slugs(articleOrder([...articles,d,e],{article_order:['b','a','c']})),['e','d','b','a','c']);});
test('empty invalid or removed cover always falls back to newest date independently of manual order and legacy featured',()=>{for(const featured_slug of ['',null,'removed'])assert.equal(featuredArticle(articles,{featured_slug,article_order:['a','b','c']}).slug,'c');assert.equal(featuredArticle([]),null);assert.equal(featuredArticle(articles,{featured_slug:'a'}).slug,'a');});
test('selected MAIN card image/title/date/category/excerpt come from the article despite legacy overrides',()=>{const settings={...defaults,featured_slug:'a',article_order:['c','b','a'],cover:'/writing/other/cover.webp',excerpt:'Old override'};const before=structuredClone(settings),dom=new JSDOM(writingCard(articles,settings)),d=dom.window.document;assert.equal(d.querySelector('img').dataset.writingImage,articles[0].cover);assert.equal(d.querySelector('img').alt,'Cover a');assert.equal(d.querySelector('h3').textContent,'A');assert.equal(d.querySelector('.writing-date').textContent,'2026-09-01 · Category a');assert.equal(d.querySelector('.writing-excerpt').textContent,'Excerpt a');assert.deepEqual(settings,before);dom.window.close();});
test('real settings handler: MAIN cover and manual order persist independently; owner badge/action clear on logout',async()=>{
 const f=await lifecycleFixture(),dom=new JSDOM('<body>',{url:'https://main.example.invalid/writing/a/'}),w=dom.window,oldFetch=globalThis.fetch;Object.assign(globalThis,{window:w,document:w.document,location:w.location,history:w.history});w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.HTMLElement.prototype.scrollIntoView=function(){};
 await f.db.query('update main_presentation set settings=$1',[JSON.stringify({featured_slug:'c',article_order:['b','a']})]);
 const before=await f.state(),send=async(body,token='qa-owner')=>{const r=await f.request(f.writing,body,token);assert.equal(r.status,200);return r.json()};globalThis.fetch=async url=>Response.json(url.endsWith('writing-content')?{schema:1,articles}:await send({operation:'read-public'},''));
 try{let card;const writing=setupWriting({url:'https://api.example.invalid',key:'public',getOwner:()=>({writingRequest:send}),onChange:()=>{card=writing.card()},onAvailability(){}});await writing.ready;assert.equal(document.querySelectorAll('.writing-main-cover,.writing-article-actions').length,0);writing.setOwner(true);await tick();const button=label=>[...document.querySelectorAll('button')].find(b=>b.textContent===label);assert.equal(document.querySelector('.writing-main-cover').closest('a').pathname,'/writing/c/');button('Set as MAIN cover').click();await tick();assert.match(card,/<h3 class="writing-article-title"><a[^>]+>A<\/a>/);assert.equal(button('MAIN cover selected').disabled,true);assert.equal(document.querySelectorAll('.writing-main-cover').length,1);let saved=await f.state();assert.deepEqual(saved.settings.article_order,before.settings.article_order);assert.deepEqual(saved.home_order,before.home_order);assert.equal(saved.settings.featured_slug,'a');
 writing.refresh();await tick();assert.equal(button('MAIN cover selected').disabled,true);assert.deepEqual([...document.querySelectorAll('.writing-index>a')].map(a=>a.pathname),['/writing/c/','/writing/b/','/writing/a/']);button('Reorder articles').click();document.querySelector('[data-index="2"][data-step="-1"]').click();document.querySelector('.writing-order-form').dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();saved=await f.state();assert.deepEqual(saved.settings.article_order,['c','a','b']);assert.equal(saved.settings.featured_slug,'a');assert.deepEqual(saved.home_order,before.home_order);writing.refresh();await tick();assert.deepEqual([...document.querySelectorAll('.writing-index>a')].map(a=>a.pathname),['/writing/c/','/writing/a/','/writing/b/']);writing.setOwner(false);assert.equal(document.querySelectorAll('.writing-main-cover,.writing-article-actions').length,0);assert.equal((await f.request(f.writing,{operation:'settings',revision:saved.revision,data:{featured_slug:'c'}},'')).status,401);
 }finally{globalThis.fetch=oldFetch;dom.window.close();await f.db.close();}
});

test('cover save finishing after navigation updates the home card; logout still rejects its late completion',async()=>{
 for(const logout of [false,true]){const dom=new JSDOM('<body>',{url:'https://main.example.invalid/writing/a/'}),w=dom.window,oldFetch=globalThis.fetch;Object.assign(globalThis,{window:w,document:w.document,location:w.location,history:w.history});w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.HTMLElement.prototype.scrollIntoView=function(){};let resolveSave,card;const state={ok:true,settings:{...defaults,featured_slug:'c',article_order:['b','a']},home_order:['writing'],revision:1};globalThis.fetch=async url=>Response.json(url.endsWith('writing-content')?{schema:1,articles}:{ok:true,settings:state.settings,home_order:state.home_order});
 try{const writing=setupWriting({url:'https://api.example.invalid',key:'public',getOwner:()=>({writingRequest:async p=>p.operation==='read-owner'?state:new Promise(r=>{resolveSave=r})}),onChange:()=>{card=writing.card()},onAvailability(){}});await writing.ready;writing.setOwner(true);await tick();[...document.querySelectorAll('button')].find(b=>b.textContent==='Set as MAIN cover').click();if(logout)writing.setOwner(false);else document.querySelector('.writing-close').click();resolveSave({...state,revision:2,settings:{...state.settings,featured_slug:'a'}});await tick();const d=new JSDOM(card);assert.equal(d.window.document.querySelector('h3').textContent,logout?'C':'A');d.window.close();assert.equal(document.querySelectorAll('.writing-article-actions').length,0);if(!logout)assert.equal(location.pathname,'/');
 }finally{globalThis.fetch=oldFetch;dom.window.close();}}
});
