import {readFile,readdir} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {stripTypeScriptTypes} from 'node:module';
export async function loadHandler(relative,exportName){let source=stripTypeScriptTypes(await readFile(new URL(relative,import.meta.url),'utf8'));source=source.replaceAll(/\.\.\/\.\.\/\.\.\/assets\/js\/([a-z-]+\.mjs)/g,(_,name)=>new URL('../../assets/js/'+name,import.meta.url).href);return (await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64')))[exportName];}
export async function lifecycleFixture(){
 const db=new PGlite();await db.exec('create role anon;create role authenticated;create role service_role bypassrls;');
 const dir=new URL('../../supabase/migrations/',import.meta.url);
 for(const name of (await readdir(dir)).sort())await db.exec(await readFile(new URL(name,dir),'utf8'));
 // Only this in-memory test database is changed; no external service/credential is used.
 await db.exec('delete from product_registry;');
 const ids=Array.from({length:5},(_,i)=>'00000000-0000-0000-0000-'+String(i+1).padStart(12,'0'));
 for(const [i,id] of ids.entries())await db.query("insert into product_registry(id,slug,name,description,maturity,deployment,visibility,operational_status,sort_order,main_url,github_url,status_note) values($1,$2,$3,$4,'Production','Public','Public','Live',$5,$6,$7,$8)",[id,'qa-product-'+(i+1),'QA Product '+String.fromCharCode(65+i),'Isolated product description '+i,(i+1)*10,'https://example.invalid/'+i,'https://github.com/example/qa','Isolated note '+i]);
 await db.query('update main_presentation set revision=0,home_order=$1,settings=$2',[JSON.stringify([ids[0],'writing',...ids.slice(1)]),JSON.stringify({featured_slug:'qa-first',article_order:['qa-first']})]);
 const auth={getUser:async token=>({data:{user:token==='qa-owner'?{id:'38531f7e-e05e-473a-a587-500b1d3aebe5',email_confirmed_at:'yes'}:token==='other'?{id:'other',email_confirmed_at:'yes'}:token==='anonymous'?{id:'38531f7e-e05e-473a-a587-500b1d3aebe5',email_confirmed_at:'yes',is_anonymous:true}:null}})};
 const client={auth,from(table){if(!['product_registry','main_presentation'].includes(table))throw Error('Unexpected test table');const filters=[];let one=false;const chain={select(){return chain},eq(k,v){filters.push([k,v]);return chain},order(){return chain},single(){one=true;return chain},async then(resolve){const rows=(await db.query('select * from '+table+(table==='product_registry'?' order by sort_order nulls last,name,id':''))).rows.filter(r=>filters.every(([k,v])=>r[k]===v));return resolve({data:one?rows[0]:rows,error:null})}};return chain},async rpc(name,args){try{let rows;if(name==='change_product_lifecycle')rows=(await db.query('select * from change_product_lifecycle($1,$2,$3)',[args.product_id,args.expected_revision,args.action])).rows;else if(name==='update_main_presentation')rows=(await db.query('select * from update_main_presentation($1,$2,$3)',[args.expected_revision,args.settings_patch,args.next_home_order])).rows;else if(name==='reorder_product_registry')return {data:(await db.query('select reorder_product_registry($1,$2,$3) as result',[args.expected,args.ordered_ids,args.expected_presentation_revision])).rows[0].result};else throw Error('Unexpected test RPC');return {data:rows,error:null}}catch(error){return {data:null,error:{code:error.code,message:error.message}}}}};
 const createRegistryHandler=await loadHandler('../../supabase/functions/registry-ops/handler.ts','createRegistryHandler');
 const createWritingHandler=await loadHandler('../../supabase/functions/writing-ops/handler.ts','createWritingHandler');
 const options={createClient:()=>client,getEnv:k=>k==='REGISTRY_API_KEY'?'qa-manager':''};
 const registry=createRegistryHandler(options),writing=createWritingHandler(options);
 const request=(handler,body,token='qa-owner')=>handler(new Request('https://qa.invalid',{method:'POST',headers:{authorization:token?'Bearer '+token:'',origin:'https://main.ycsu.cc','content-type':'application/json'},body:JSON.stringify(body)}));
 return {db,ids,registry,writing,request,async rows(){return (await db.query('select * from product_registry order by sort_order nulls last,name,id')).rows},async state(){return (await db.query('select * from main_presentation')).rows[0]},async change(id,action,extra={}){const p=(await db.query('select * from product_registry where id=$1',[id])).rows[0];return request(registry,{operation:'lifecycle',data:{id,revision:p.lifecycle_revision,action,...(action==='delete'?{confirm:true}:{}),...extra}})}};
}
